name: Deploy to Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_TEST }}

      - name: Copy files via SCP
        env:
          GCE_IP_ADDRESS_TEST: ${{ secrets.GCE_IP_ADDRESS_TEST }}
        run: scp -r . gskyt_01@$GCE_IP_ADDRESS_TEST:/home/gskyt_01/discord-bot

      - name: SSH and run deploy commands
        env:
          GCE_IP_ADDRESS_TEST: ${{ secrets.GCE_IP_ADDRESS_TEST }}
        run: |
          ssh gskyt_01@$GCE_IP_ADDRESS_TEST << 'EOF'
          cd /home/gskyt_01/discord-bot
          git pull origin main
          npm install
          pm2 restart discord-bot
          EOF
